ALTER TABLE equity_ohlcv_daily ADD COLUMN IF NOT EXISTS ema10 DOUBLE;
ALTER TABLE equity_ohlcv_daily ADD COLUMN IF NOT EXISTS ema20 DOUBLE;
ALTER TABLE equity_ohlcv_daily ADD COLUMN IF NOT EXISTS ema50 DOUBLE;
ALTER TABLE equity_ohlcv_daily ADD COLUMN IF NOT EXISTS ema200 DOUBLE;
ALTER TABLE equity_ohlcv_daily ADD COLUMN IF NOT EXISTS volema10 DOUBLE;
ALTER TABLE equity_ohlcv_daily ADD COLUMN IF NOT EXISTS volema20 DOUBLE;
